name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_NAME: extract


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: 安装依赖
        run: |
          npm install
          # peer dep
          npm install tslib

      - name: 编译
        run: |
          make build

      - name: 打包
        run: |
          zip extract.zip -r src fn_list.json

      - uses: actions/upload-artifact@v2
        with:
          name: extract
          path: extract.zip
